FROM openjdk:8-jdk-alpine
MAINTAINER bilalachraf
COPY target/config-server-demo-0.0.1-SNAPSHOT.jar config-server-demo-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/config-server-demo-0.0.1-SNAPSHOT.jar"]