FROM openjdk:8-jdk-alpine
MAINTAINER bilalachraf
COPY target/data-analytics-service-0.0.1-SNAPSHOT.jar data-analytics-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/data-analytics-service-0.0.1-SNAPSHOT.jar"]