FROM openjdk:8-jdk-alpine
MAINTAINER bilalachraf
COPY target/billing-supplier-service-0.0.1-SNAPSHOT.jar billing-supplier-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/billing-supplier-service-0.0.1-SNAPSHOT.jar"]